version: "3.8"
services:
  identity-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    ports: ["5435:5432"]

  posts-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts_db
    volumes:
      - posts_db_data:/var/lib/postgresql/data
    ports: ["5436:5432"]

  feeds-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feeds_db
    volumes:
      - feeds_db_data:/var/lib/postgresql/data
    ports: ["5434:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000"]
    volumes:
      - minio_data:/data

  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
    ports: ["9092:9092"]
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  identity:
    build: ./identity
    volumes:
      - ./identity:/app
    depends_on: ["identity-db", "minio"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@identity-db:5432/identity_db
      DJANGO_SECRET_KEY: change-me
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
    ports: ["8000:8000"]

  posts:
    build: ./posts
    depends_on: ["posts-db", "redpanda", "minio"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@posts-db:5436/posts_db
      REDPANDA_BROKERS: redpanda:9092
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
    ports: ["8001:8001"]

  feeds:
    build: ./feeds
    depends_on: ["feeds-db", "redpanda", "redis"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@feeds-db:5434/feeds_db
      REDPANDA_BROKERS: redpanda:9092
      REDIS_URL: redis://redis:6379
    ports: ["8002:8002"]

  frontend:
    build: ./frontend
    depends_on: ["identity", "posts", "feeds"]
    ports: ["5173:5173"]

volumes:
  identity_db_data:
  posts_db_data:
  feeds_db_data:
  minio_data:
  redpanda_data:
